images:
  al2023-6-1:
    ssm_path: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64
    instance_type: m6g.large
    user_data_file: al2023-6.1.yaml
  ubuntu-2204:
    ssm_path: /aws/service/canonical/ubuntu/server/jammy/stable/current/arm64/hvm/ebs-gp2/ami-id
    instance_type: m6g.large
    user_data_file: ubuntu2204.yaml
